learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),  # https://stackoverflow.com/a/50011971/5717580
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs."""

from django.urls import path
from . import views


app_name = 'learning_logs'  # https://stackoverflow.com/a/50011971/5717580

urlpatterns = [
    # homepage
    path('', views.index, name='index'),  # remember adding the name kw-arg
    # topics
    path('topics/', views.topics, name='topics'),
]

learning_logs/models.py
from django.db import models


class Topic(models.Model):  # singular turns to Plural in admin
    """A topic the user is learning about."""
    text = models.CharField(max_length=200)  # talk about SQL
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text


class Entry(models.Model):
    """Something specific learned about a Topic."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)  # show that it needs something set on_delete
    text = models.TextField()  # let's not limit this one
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return f"{self.text[:50]}..."  # display a clipped version of the entry

learning_logs/views.py
from django.shortcuts import render
from .models import Topic


# Create your views here.
def index(request):
    """The home page for learning logs."""
    return render(request, 'learning_logs/index.html')

def topics(request):
    """Displays a list of all available topics."""
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Learning Log</title>
</head>
<body>
    <nav>
        <a href="{% url 'learning_logs:index' %}">Learning Logs</a>
        <a href="{% url 'learning_logs:topics' %}">All Topics</a>
    </nav>
    {% block content %}
    
    {% endblock %}
</body>
</html>

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}

    <h1>Learning Log</h1>
    <p>This app helps you keep track of what you're learning about.</p>

{% endblock %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block content %}
    
    <h1>Topics</h1>

    <ul>
    {% for topic in topics %}
        <li>{{ topic }}</li>
    {% empty %}
        <li>No topics added yet</li>
    {% endfor %}
    </ul>

{% endblock %}